@startuml

title RDCU pour redemarerJeu
participant ":JeuDeDes" as c
participant "joueurs: \nMap<String, Joueur>" as jm

-> c : redemarrerJeu()
c -> jm : clear()
note right of c : Selon Contrôleur(JeuDeDes est en objet racine)
note right of jm : Selon Expert
  
@enduml